export interface PearsEvent {
  id: string
  slug: string
  title: string
  date: string
  time: string
  location: string
  city: string
  state: string
  address: string
  categories: string[]
  spots: number
  spotsLeft: number
  featured: boolean
  description: string
  image: string
  ticketPrice: number
  earlyBirdPrice: number
  earlyBirdDeadline: string
  registrationDeadline: string
  trackLength: string
  surface: string
  facilities: string[]
  schedule: { time: string; activity: string }[]
  mapUrl: string
}

export const eventsData: PearsEvent[] = [
  {
    id: "1",
    slug: "pears-summer-championship-2025",
    title: "PEARS Summer Championship",
    date: "January 15, 2025",
    time: "8:00 AM - 2:00 PM",
    location: "Sydney Olympic Park",
    city: "Sydney",
    state: "NSW",
    address: "Olympic Boulevard, Sydney Olympic Park NSW 2127",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 120,
    spotsLeft: 34,
    featured: true,
    description:
      "The flagship PEARS event of the summer season! Join us at the iconic Sydney Olympic Park for a day of thrilling races, family fun, and championship glory. This premier event features multiple age categories and attracts top young riders from across Australia.",
    image: "/kids-pushbike-racing-summer-championship-event.jpg",
    ticketPrice: 45,
    earlyBirdPrice: 35,
    earlyBirdDeadline: "December 31, 2024",
    registrationDeadline: "January 10, 2025",
    trackLength: "75m",
    surface: "Synthetic grass with rubber base",
    facilities: ["First Aid Station", "Food Vendors", "Covered Seating", "Toilets", "Parking", "Medal Ceremony Stage"],
    schedule: [
      { time: "7:00 AM", activity: "Gates Open & Registration" },
      { time: "8:00 AM", activity: "Opening Ceremony" },
      { time: "8:30 AM", activity: "2-3 Years Heats" },
      { time: "9:30 AM", activity: "3-4 Years Heats" },
      { time: "10:30 AM", activity: "Morning Break & Refreshments" },
      { time: "11:00 AM", activity: "4-5 Years Heats" },
      { time: "12:00 PM", activity: "5-6 Years Heats" },
      { time: "1:00 PM", activity: "Finals All Categories" },
      { time: "2:00 PM", activity: "Medal Ceremony & Closing" },
    ],
    mapUrl: "https://maps.google.com/?q=Sydney+Olympic+Park",
  },
  {
    id: "2",
    slug: "melbourne-mini-racers-cup",
    title: "Melbourne Mini Racers Cup",
    date: "February 8, 2025",
    time: "9:00 AM - 1:00 PM",
    location: "Flemington Racecourse",
    city: "Melbourne",
    state: "VIC",
    address: "448 Epsom Road, Flemington VIC 3031",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years"],
    spots: 80,
    spotsLeft: 22,
    featured: false,
    description:
      "Race on the grounds of the famous Flemington Racecourse! This exciting event brings the spirit of Australian racing to our youngest competitors. A perfect introduction to competitive pushbike racing in a world-class venue.",
    image: "/kids-balance-bike-race-melbourne-event.jpg",
    ticketPrice: 40,
    earlyBirdPrice: 32,
    earlyBirdDeadline: "January 25, 2025",
    registrationDeadline: "February 3, 2025",
    trackLength: "60m",
    surface: "Natural grass",
    facilities: ["First Aid Station", "Cafe On-site", "Shaded Areas", "Toilets", "Free Parking"],
    schedule: [
      { time: "8:00 AM", activity: "Gates Open & Registration" },
      { time: "9:00 AM", activity: "Welcome & Safety Briefing" },
      { time: "9:30 AM", activity: "2-3 Years Races" },
      { time: "10:30 AM", activity: "3-4 Years Races" },
      { time: "11:30 AM", activity: "4-5 Years Races" },
      { time: "12:30 PM", activity: "Medal Ceremony" },
    ],
    mapUrl: "https://maps.google.com/?q=Flemington+Racecourse",
  },
  {
    id: "3",
    slug: "brisbane-balance-bike-festival",
    title: "Brisbane Balance Bike Festival",
    date: "February 22, 2025",
    time: "8:30 AM - 12:30 PM",
    location: "South Bank Parklands",
    city: "Brisbane",
    state: "QLD",
    address: "South Bank Parklands, South Brisbane QLD 4101",
    categories: ["3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 100,
    spotsLeft: 45,
    featured: false,
    description:
      "Experience the beautiful South Bank Parklands while your little ones compete! This festival-style event combines racing with family activities, food trucks, and entertainment. Perfect for making a day trip out of race day.",
    image: "/kids-pushbike-festival-brisbane-parklands.jpg",
    ticketPrice: 38,
    earlyBirdPrice: 30,
    earlyBirdDeadline: "February 8, 2025",
    registrationDeadline: "February 17, 2025",
    trackLength: "65m",
    surface: "Compacted gravel path",
    facilities: ["First Aid Station", "Food Trucks", "Playground Nearby", "Toilets", "Public Transport Access"],
    schedule: [
      { time: "7:30 AM", activity: "Gates Open" },
      { time: "8:30 AM", activity: "Opening Ceremony" },
      { time: "9:00 AM", activity: "3-4 Years Heats" },
      { time: "10:00 AM", activity: "4-5 Years Heats" },
      { time: "11:00 AM", activity: "5-6 Years Heats" },
      { time: "12:00 PM", activity: "Finals & Awards" },
    ],
    mapUrl: "https://maps.google.com/?q=South+Bank+Parklands+Brisbane",
  },
  {
    id: "4",
    slug: "perth-junior-sprint-series",
    title: "Perth Junior Sprint Series",
    date: "March 5, 2025",
    time: "9:00 AM - 2:00 PM",
    location: "Langley Park",
    city: "Perth",
    state: "WA",
    address: "Riverside Drive, Perth WA 6000",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 90,
    spotsLeft: 67,
    featured: true,
    description:
      "Perth's premier pushbike racing event with stunning views of the Swan River! All four age categories compete in this full-day event featuring sprint races and a special championship round for top performers.",
    image: "/kids-bike-sprint-race-perth-riverside.jpg",
    ticketPrice: 42,
    earlyBirdPrice: 34,
    earlyBirdDeadline: "February 19, 2025",
    registrationDeadline: "February 28, 2025",
    trackLength: "70m",
    surface: "Synthetic track surface",
    facilities: ["First Aid Station", "Food Vendors", "Riverside Views", "Toilets", "City Parking Nearby", "BBQ Areas"],
    schedule: [
      { time: "8:00 AM", activity: "Venue Opens" },
      { time: "9:00 AM", activity: "Welcome Address" },
      { time: "9:30 AM", activity: "2-3 Years Sprint" },
      { time: "10:15 AM", activity: "3-4 Years Sprint" },
      { time: "11:00 AM", activity: "Lunch Break" },
      { time: "12:00 PM", activity: "4-5 Years Sprint" },
      { time: "12:45 PM", activity: "5-6 Years Sprint" },
      { time: "1:30 PM", activity: "Championship Finals" },
      { time: "2:00 PM", activity: "Presentations" },
    ],
    mapUrl: "https://maps.google.com/?q=Langley+Park+Perth",
  },
  {
    id: "5",
    slug: "adelaide-autumn-classic",
    title: "Adelaide Autumn Classic",
    date: "March 22, 2025",
    time: "9:00 AM - 1:00 PM",
    location: "Adelaide Parklands",
    city: "Adelaide",
    state: "SA",
    address: "War Memorial Drive, North Adelaide SA 5006",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 75,
    spotsLeft: 52,
    featured: false,
    description:
      "As autumn arrives, join us in the beautiful Adelaide Parklands for a classic day of pushbike racing. This intimate event offers a friendly atmosphere perfect for first-time racers and experienced riders alike.",
    image: "/kids-balance-bike-race-autumn-park-adelaide.jpg",
    ticketPrice: 38,
    earlyBirdPrice: 30,
    earlyBirdDeadline: "March 8, 2025",
    registrationDeadline: "March 17, 2025",
    trackLength: "55m",
    surface: "Grass with marked lanes",
    facilities: ["First Aid Station", "BYO Picnic Area", "Toilets", "Street Parking"],
    schedule: [
      { time: "8:30 AM", activity: "Registration Opens" },
      { time: "9:00 AM", activity: "Event Begins" },
      { time: "9:30 AM", activity: "Youngest Categories" },
      { time: "11:00 AM", activity: "Older Categories" },
      { time: "12:30 PM", activity: "Medal Ceremony" },
    ],
    mapUrl: "https://maps.google.com/?q=Adelaide+Parklands",
  },
  {
    id: "6",
    slug: "gold-coast-beach-blast",
    title: "Gold Coast Beach Blast",
    date: "April 5, 2025",
    time: "8:00 AM - 12:00 PM",
    location: "Broadbeach Parklands",
    city: "Gold Coast",
    state: "QLD",
    address: "T.E. Peters Drive, Broadbeach QLD 4218",
    categories: ["3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 85,
    spotsLeft: 71,
    featured: true,
    description:
      "Feel the coastal vibes at this beachside racing event! The Gold Coast Beach Blast combines the excitement of pushbike racing with a day at the beach. Stay after the event to enjoy the surf and sand!",
    image: "/kids-pushbike-race-beachside-gold-coast.jpg",
    ticketPrice: 40,
    earlyBirdPrice: 32,
    earlyBirdDeadline: "March 22, 2025",
    registrationDeadline: "March 31, 2025",
    trackLength: "60m",
    surface: "Hard-packed sand and grass",
    facilities: ["First Aid Station", "Beach Access", "Cafes Nearby", "Toilets", "Paid Parking"],
    schedule: [
      { time: "7:30 AM", activity: "Arrival & Setup" },
      { time: "8:00 AM", activity: "Event Kickoff" },
      { time: "8:30 AM", activity: "3-4 Years Heats" },
      { time: "9:30 AM", activity: "4-5 Years Heats" },
      { time: "10:30 AM", activity: "5-6 Years Heats" },
      { time: "11:30 AM", activity: "Finals & Awards" },
    ],
    mapUrl: "https://maps.google.com/?q=Broadbeach+Parklands",
  },
  {
    id: "7",
    slug: "canberra-capital-cup",
    title: "Canberra Capital Cup",
    date: "April 19, 2025",
    time: "9:30 AM - 1:30 PM",
    location: "Commonwealth Park",
    city: "Canberra",
    state: "ACT",
    address: "Commonwealth Park, Parkes ACT 2600",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 70,
    spotsLeft: 58,
    featured: false,
    description:
      "Race in the nation's capital! The Canberra Capital Cup takes place in the stunning Commonwealth Park with views of Lake Burley Griffin. A prestigious event that draws competitors from across the region.",
    image: "/kids-bike-race-canberra-commonwealth-park.jpg",
    ticketPrice: 42,
    earlyBirdPrice: 34,
    earlyBirdDeadline: "April 5, 2025",
    registrationDeadline: "April 14, 2025",
    trackLength: "65m",
    surface: "Maintained grass",
    facilities: ["First Aid Station", "Lake Views", "Playground", "Toilets", "Parking"],
    schedule: [
      { time: "9:00 AM", activity: "Gates Open" },
      { time: "9:30 AM", activity: "Official Start" },
      { time: "10:00 AM", activity: "Morning Races" },
      { time: "12:00 PM", activity: "Lunch Break" },
      { time: "12:30 PM", activity: "Finals" },
      { time: "1:30 PM", activity: "Closing Ceremony" },
    ],
    mapUrl: "https://maps.google.com/?q=Commonwealth+Park+Canberra",
  },
  {
    id: "8",
    slug: "tasmania-tiger-chase",
    title: "Tasmania Tiger Chase",
    date: "May 10, 2025",
    time: "10:00 AM - 2:00 PM",
    location: "Queens Domain",
    city: "Hobart",
    state: "TAS",
    address: "Queens Domain, Hobart TAS 7000",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 60,
    spotsLeft: 48,
    featured: false,
    description:
      "Tasmania's only PEARS-sanctioned event! The Tiger Chase brings pushbike racing to the Apple Isle with spectacular mountain backdrop views. Don't miss this unique racing experience in beautiful Hobart.",
    image: "/kids-pushbike-race-tasmania-hobart-mountain.jpg",
    ticketPrice: 45,
    earlyBirdPrice: 36,
    earlyBirdDeadline: "April 26, 2025",
    registrationDeadline: "May 5, 2025",
    trackLength: "55m",
    surface: "Natural grass",
    facilities: ["First Aid Station", "Mountain Views", "Toilets", "Street Parking", "Warm Shelter Available"],
    schedule: [
      { time: "9:30 AM", activity: "Check-in Opens" },
      { time: "10:00 AM", activity: "Welcome" },
      { time: "10:30 AM", activity: "Racing Begins" },
      { time: "1:00 PM", activity: "Championship Rounds" },
      { time: "2:00 PM", activity: "Prize Giving" },
    ],
    mapUrl: "https://maps.google.com/?q=Queens+Domain+Hobart",
  },
  {
    id: "9",
    slug: "national-championship-2025",
    title: "PEARS National Championship 2025",
    date: "June 14-15, 2025",
    time: "8:00 AM - 4:00 PM",
    location: "Melbourne Sports Hub",
    city: "Melbourne",
    state: "VIC",
    address: "Olympic Boulevard, Melbourne VIC 3000",
    categories: ["2-3 Years", "3-4 Years", "4-5 Years", "5-6 Years"],
    spots: 200,
    spotsLeft: 142,
    featured: true,
    description:
      "The ultimate PEARS event! Our two-day National Championship brings together the best young riders from across Australia to compete for national titles. Features qualifying rounds on day one and championship finals on day two. The most prestigious event on the PEARS calendar.",
    image: "/kids-pushbike-national-championship-big-event.jpg",
    ticketPrice: 75,
    earlyBirdPrice: 60,
    earlyBirdDeadline: "May 31, 2025",
    registrationDeadline: "June 7, 2025",
    trackLength: "80m",
    surface: "Professional synthetic track",
    facilities: [
      "Medical Team On-site",
      "Catering",
      "VIP Areas",
      "Live Commentary",
      "Big Screens",
      "Covered Grandstand",
      "Parking",
      "Merchandise Store",
    ],
    schedule: [
      { time: "Day 1 - 8:00 AM", activity: "Registration & Bike Check" },
      { time: "Day 1 - 9:00 AM", activity: "Opening Ceremony" },
      { time: "Day 1 - 10:00 AM", activity: "Qualifying Heats All Categories" },
      { time: "Day 1 - 4:00 PM", activity: "Day 1 Closes" },
      { time: "Day 2 - 8:00 AM", activity: "Gates Open" },
      { time: "Day 2 - 9:00 AM", activity: "Semi-Finals" },
      { time: "Day 2 - 12:00 PM", activity: "Lunch & Entertainment" },
      { time: "Day 2 - 1:00 PM", activity: "Championship Finals" },
      { time: "Day 2 - 3:00 PM", activity: "National Champion Crowning" },
      { time: "Day 2 - 4:00 PM", activity: "Closing Ceremony" },
    ],
    mapUrl: "https://maps.google.com/?q=Melbourne+Sports+Hub",
  },
]

export function getEventBySlug(slug: string): PearsEvent | undefined {
  return eventsData.find((event) => event.slug === slug)
}

export function getFeaturedEvents(): PearsEvent[] {
  return eventsData.filter((event) => event.featured)
}

export function getUpcomingEvents(limit?: number): PearsEvent[] {
  const sorted = [...eventsData].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
  return limit ? sorted.slice(0, limit) : sorted
}
