export interface Rider {
  id: string
  slug: string
  name: string
  age: number
  category: string
  location: string
  state: string
  points: number
  rank: number
  previousRank: number
  races: number
  wins: number
  podiums: number
  bestTime: string
  joinedYear: number
  bio: string
  avatar: string
}

export const ridersData: Rider[] = [
  // 2-3 Years
  {
    id: "1",
    slug: "oliver-thompson",
    name: "Oliver Thompson",
    age: 3,
    category: "2-3 Years",
    location: "Sydney",
    state: "NSW",
    points: 2450,
    rank: 1,
    previousRank: 1,
    races: 8,
    wins: 5,
    podiums: 7,
    bestTime: "12.4s",
    joinedYear: 2024,
    bio: "Oliver started racing at just 2 years old and quickly showed natural talent on the balance bike.",
    avatar: "/young-boy-toddler-portrait-happy.jpg",
  },
  {
    id: "2",
    slug: "emma-wilson",
    name: "Emma Wilson",
    age: 3,
    category: "2-3 Years",
    location: "Melbourne",
    state: "VIC",
    points: 2380,
    rank: 2,
    previousRank: 3,
    races: 9,
    wins: 4,
    podiums: 8,
    bestTime: "12.6s",
    joinedYear: 2024,
    bio: "Emma is known for her fearless racing style and infectious enthusiasm.",
    avatar: "/young-girl-toddler-portrait-smiling.jpg",
  },
  {
    id: "3",
    slug: "liam-chen",
    name: "Liam Chen",
    age: 2,
    category: "2-3 Years",
    location: "Brisbane",
    state: "QLD",
    points: 2290,
    rank: 3,
    previousRank: 4,
    races: 7,
    wins: 3,
    podiums: 5,
    bestTime: "13.1s",
    joinedYear: 2024,
    bio: "The youngest competitor in the top rankings, Liam shows incredible promise.",
    avatar: "/asian-toddler-boy-portrait-cute.jpg",
  },
  {
    id: "4",
    slug: "ava-martinez",
    name: "Ava Martinez",
    age: 3,
    category: "2-3 Years",
    location: "Perth",
    state: "WA",
    points: 2150,
    rank: 4,
    previousRank: 2,
    races: 8,
    wins: 3,
    podiums: 6,
    bestTime: "12.8s",
    joinedYear: 2023,
    bio: "Ava brings determination and focus to every race she enters.",
    avatar: "/latina-toddler-girl-portrait-happy.jpg",
  },
  {
    id: "5",
    slug: "noah-johnson",
    name: "Noah Johnson",
    age: 2,
    category: "2-3 Years",
    location: "Adelaide",
    state: "SA",
    points: 2080,
    rank: 5,
    previousRank: 5,
    races: 6,
    wins: 2,
    podiums: 4,
    bestTime: "13.3s",
    joinedYear: 2024,
    bio: "Noah loves the atmosphere of race day and always has a smile on his face.",
    avatar: "/toddler-boy-blonde-portrait.jpg",
  },
  {
    id: "6",
    slug: "mia-patel",
    name: "Mia Patel",
    age: 3,
    category: "2-3 Years",
    location: "Gold Coast",
    state: "QLD",
    points: 1950,
    rank: 6,
    previousRank: 7,
    races: 7,
    wins: 2,
    podiums: 4,
    bestTime: "13.0s",
    joinedYear: 2024,
    bio: "Mia's parents say she's been obsessed with bikes since before she could walk.",
    avatar: "/indian-toddler-girl-portrait.jpg",
  },
  {
    id: "7",
    slug: "jack-murphy",
    name: "Jack Murphy",
    age: 2,
    category: "2-3 Years",
    location: "Hobart",
    state: "TAS",
    points: 1820,
    rank: 7,
    previousRank: 6,
    races: 5,
    wins: 1,
    podiums: 3,
    bestTime: "13.5s",
    joinedYear: 2024,
    bio: "Tasmania's rising star, Jack is building his skills with every event.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "8",
    slug: "lily-nguyen",
    name: "Lily Nguyen",
    age: 3,
    category: "2-3 Years",
    location: "Canberra",
    state: "ACT",
    points: 1710,
    rank: 8,
    previousRank: 8,
    races: 6,
    wins: 1,
    podiums: 3,
    bestTime: "13.2s",
    joinedYear: 2024,
    bio: "Lily balances her racing with a love of arts and crafts.",
    avatar: "/placeholder.svg?height=200&width=200",
  },

  // 3-4 Years
  {
    id: "9",
    slug: "sophia-brown",
    name: "Sophia Brown",
    age: 4,
    category: "3-4 Years",
    location: "Melbourne",
    state: "VIC",
    points: 3120,
    rank: 1,
    previousRank: 1,
    races: 12,
    wins: 8,
    podiums: 11,
    bestTime: "10.8s",
    joinedYear: 2023,
    bio: "Sophia is the defending champion in her age group and shows no signs of slowing down.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "10",
    slug: "jack-williams",
    name: "Jack Williams",
    age: 4,
    category: "3-4 Years",
    location: "Sydney",
    state: "NSW",
    points: 3050,
    rank: 2,
    previousRank: 3,
    races: 11,
    wins: 6,
    podiums: 9,
    bestTime: "10.9s",
    joinedYear: 2023,
    bio: "Jack has been steadily climbing the rankings with consistent performances.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "11",
    slug: "mia-taylor",
    name: "Mia Taylor",
    age: 3,
    category: "3-4 Years",
    location: "Brisbane",
    state: "QLD",
    points: 2980,
    rank: 3,
    previousRank: 2,
    races: 10,
    wins: 5,
    podiums: 8,
    bestTime: "11.2s",
    joinedYear: 2023,
    bio: "One of the younger competitors in this category, Mia punches well above her weight.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "12",
    slug: "ethan-davis",
    name: "Ethan Davis",
    age: 4,
    category: "3-4 Years",
    location: "Perth",
    state: "WA",
    points: 2850,
    rank: 4,
    previousRank: 5,
    races: 11,
    wins: 4,
    podiums: 7,
    bestTime: "11.0s",
    joinedYear: 2023,
    bio: "Ethan's technical riding skills make him a formidable competitor on any track.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "13",
    slug: "charlotte-miller",
    name: "Charlotte Miller",
    age: 4,
    category: "3-4 Years",
    location: "Gold Coast",
    state: "QLD",
    points: 2720,
    rank: 5,
    previousRank: 5,
    races: 9,
    wins: 3,
    podiums: 6,
    bestTime: "11.3s",
    joinedYear: 2023,
    bio: "Charlotte loves the beach almost as much as she loves racing.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "14",
    slug: "lucas-kim",
    name: "Lucas Kim",
    age: 4,
    category: "3-4 Years",
    location: "Sydney",
    state: "NSW",
    points: 2580,
    rank: 6,
    previousRank: 7,
    races: 10,
    wins: 3,
    podiums: 5,
    bestTime: "11.4s",
    joinedYear: 2024,
    bio: "A newcomer who has quickly established himself in the top ranks.",
    avatar: "/placeholder.svg?height=200&width=200",
  },

  // 4-5 Years
  {
    id: "15",
    slug: "james-anderson",
    name: "James Anderson",
    age: 5,
    category: "4-5 Years",
    location: "Sydney",
    state: "NSW",
    points: 3850,
    rank: 1,
    previousRank: 2,
    races: 15,
    wins: 10,
    podiums: 14,
    bestTime: "9.2s",
    joinedYear: 2022,
    bio: "James is a PEARS veteran who has competed in over 30 events across his career.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "16",
    slug: "amelia-white",
    name: "Amelia White",
    age: 5,
    category: "4-5 Years",
    location: "Melbourne",
    state: "VIC",
    points: 3780,
    rank: 2,
    previousRank: 1,
    races: 14,
    wins: 9,
    podiums: 13,
    bestTime: "9.3s",
    joinedYear: 2022,
    bio: "A former national champion, Amelia remains one of the top competitors.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "17",
    slug: "lucas-harris",
    name: "Lucas Harris",
    age: 5,
    category: "4-5 Years",
    location: "Perth",
    state: "WA",
    points: 3650,
    rank: 3,
    previousRank: 3,
    races: 13,
    wins: 7,
    podiums: 11,
    bestTime: "9.5s",
    joinedYear: 2022,
    bio: "Lucas represents Western Australia with pride at every national event.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "18",
    slug: "isabella-clark",
    name: "Isabella Clark",
    age: 4,
    category: "4-5 Years",
    location: "Brisbane",
    state: "QLD",
    points: 3520,
    rank: 4,
    previousRank: 6,
    races: 14,
    wins: 6,
    podiums: 10,
    bestTime: "9.7s",
    joinedYear: 2023,
    bio: "Isabella has rocketed up the rankings this season with powerful performances.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "19",
    slug: "mason-lee",
    name: "Mason Lee",
    age: 5,
    category: "4-5 Years",
    location: "Adelaide",
    state: "SA",
    points: 3410,
    rank: 5,
    previousRank: 4,
    races: 12,
    wins: 5,
    podiums: 9,
    bestTime: "9.8s",
    joinedYear: 2023,
    bio: "South Australia's top-ranked rider in this age group.",
    avatar: "/placeholder.svg?height=200&width=200",
  },

  // 5-6 Years
  {
    id: "20",
    slug: "benjamin-walker",
    name: "Benjamin Walker",
    age: 6,
    category: "5-6 Years",
    location: "Melbourne",
    state: "VIC",
    points: 4520,
    rank: 1,
    previousRank: 1,
    races: 18,
    wins: 14,
    podiums: 17,
    bestTime: "8.1s",
    joinedYear: 2021,
    bio: "The dominant force in kids pushbike racing. Benjamin holds multiple national records and is eyeing a transition to pedal bikes.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "21",
    slug: "olivia-moore",
    name: "Olivia Moore",
    age: 6,
    category: "5-6 Years",
    location: "Sydney",
    state: "NSW",
    points: 4450,
    rank: 2,
    previousRank: 3,
    races: 17,
    wins: 11,
    podiums: 15,
    bestTime: "8.3s",
    joinedYear: 2021,
    bio: "Olivia's competitive spirit and sportsmanship make her a fan favorite.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "22",
    slug: "william-scott",
    name: "William Scott",
    age: 6,
    category: "5-6 Years",
    location: "Brisbane",
    state: "QLD",
    points: 4380,
    rank: 3,
    previousRank: 4,
    races: 16,
    wins: 10,
    podiums: 14,
    bestTime: "8.4s",
    joinedYear: 2021,
    bio: "A technical master who excels on challenging track layouts.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "23",
    slug: "chloe-young",
    name: "Chloe Young",
    age: 5,
    category: "5-6 Years",
    location: "Perth",
    state: "WA",
    points: 4210,
    rank: 4,
    previousRank: 2,
    races: 17,
    wins: 9,
    podiums: 13,
    bestTime: "8.5s",
    joinedYear: 2022,
    bio: "The youngest in the top 5 of this category, Chloe is one to watch.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "24",
    slug: "henry-king",
    name: "Henry King",
    age: 6,
    category: "5-6 Years",
    location: "Gold Coast",
    state: "QLD",
    points: 4050,
    rank: 5,
    previousRank: 5,
    races: 15,
    wins: 8,
    podiums: 12,
    bestTime: "8.6s",
    joinedYear: 2022,
    bio: "Henry combines speed with strategy to consistently finish on the podium.",
    avatar: "/placeholder.svg?height=200&width=200",
  },
]

export function getRiderBySlug(slug: string): Rider | undefined {
  return ridersData.find((rider) => rider.slug === slug)
}

export function getRidersByCategory(category: string): Rider[] {
  return ridersData.filter((rider) => rider.category === category).sort((a, b) => a.rank - b.rank)
}

export function getTopRiders(limit = 10): Rider[] {
  return [...ridersData].sort((a, b) => b.points - a.points).slice(0, limit)
}
